apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-stream-config
  namespace: omni-streaming
data:
  stream.config.json: |
    {
      "source": "stream",
      "stream": {
        "appServer": "http(s)://<YOUR-APP-SERVER>",
        "streamServer": "http(s)://<YOUR-STREAM-SERVER>",
        "appId": "bottle-filling-twin",
        "appVersion": "1.0.0",
        "profile": "bottle-filling-twin-default"
      }
    }
