// Copyright (C) 2025 - 2026 ANSYS, Inc. and/or its affiliates.
// SPDX-License-Identifier: MIT
//
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/**
 * Streaming Slice
 *
 * Manages streaming-related state including WebRTC connection, media settings, and stream control
 */

// Note: This is a TypeScript implementation without Redux Toolkit to avoid dependencies
// In a real implementation, you would install @reduxjs/toolkit and react-redux

// Streaming state interface
export interface StreamingState {
  // Stream readiness and connection
  streamReady: boolean;
  isConnecting: boolean;
  isConnected: boolean;

  // WebRTC configuration
  signalingServer: string;
  signalingPort: number;
  mediaServer: string;
  mediaPort: number;
  backendUrl: string;
  accessToken: string;

  // Stream configuration
  videoElementId: string;
  audioElementId: string;
  width: number;
  height: number;
  fps: number;
  nativeTouchEvents: boolean;

  // Media settings
  audioMuted: boolean;
  videoMuted: boolean;
  microphoneEnabled: boolean;

  // Stream quality and performance
  connectionQuality: 'excellent' | 'good' | 'fair' | 'poor' | 'unknown';
  latency: number; // in milliseconds
  bitrate: number; // in kbps
  frameRate: number;

  // Error handling
  connectionError: string | null;
  lastConnectionAttempt: number | null;
  reconnectAttempts: number;
  maxReconnects: number;

  // Stream events log
  streamEvents: StreamEvent[];
}

export interface StreamEvent {
  timestamp: number;
  type: 'info' | 'warning' | 'error';
  action: string;
  status: string;
  message?: string;
  data?: unknown;
}

// Stream connection configuration interface for Redux state
export interface StreamConnectionConfig {
  signalingServer: string;
  signalingPort: number;
  mediaServer: string;
  mediaPort: number;
  backendUrl: string;
  sessionId: string;
  accessToken?: string;
  width?: number;
  height?: number;
  fps?: number;
}

// Initial state
const initialState: StreamingState = {
  streamReady: false,
  isConnecting: false,
  isConnected: false,

  signalingServer: '',
  signalingPort: 0,
  mediaServer: '',
  mediaPort: 0,
  backendUrl: '',
  accessToken: '',

  videoElementId: 'remote-video',
  audioElementId: 'remote-audio',
  width: 1920,
  height: 1080,
  fps: 60,
  nativeTouchEvents: true,

  audioMuted: false,
  videoMuted: false,
  microphoneEnabled: false,

  connectionQuality: 'unknown',
  latency: 0,
  bitrate: 0,
  frameRate: 0,

  connectionError: null,
  lastConnectionAttempt: null,
  reconnectAttempts: 0,
  maxReconnects: 20,

  streamEvents: [],
};

// Action types (would be generated by createSlice in real implementation)
export const STREAMING_ACTIONS = {
  // Connection management
  SET_STREAM_READY: 'streaming/setStreamReady',
  SET_CONNECTING: 'streaming/setConnecting',
  SET_CONNECTED: 'streaming/setConnected',

  // Configuration
  SET_STREAM_CONFIG: 'streaming/setStreamConfig',
  UPDATE_STREAM_SETTINGS: 'streaming/updateStreamSettings',

  // Media controls
  SET_AUDIO_MUTED: 'streaming/setAudioMuted',
  SET_VIDEO_MUTED: 'streaming/setVideoMuted',
  SET_MICROPHONE_ENABLED: 'streaming/setMicrophoneEnabled',

  // Quality monitoring
  UPDATE_CONNECTION_QUALITY: 'streaming/updateConnectionQuality',
  UPDATE_STREAM_METRICS: 'streaming/updateStreamMetrics',

  // Error handling
  SET_CONNECTION_ERROR: 'streaming/setConnectionError',
  CLEAR_CONNECTION_ERROR: 'streaming/clearConnectionError',
  INCREMENT_RECONNECT_ATTEMPTS: 'streaming/incrementReconnectAttempts',
  RESET_RECONNECT_ATTEMPTS: 'streaming/resetReconnectAttempts',

  // Events
  ADD_STREAM_EVENT: 'streaming/addStreamEvent',
  CLEAR_STREAM_EVENTS: 'streaming/clearStreamEvents',

  // Reset
  RESET_STREAMING_STATE: 'streaming/resetStreamingState',
} as const;

// Action creators (simplified version without Redux Toolkit)
export const streamingActions = {
  setStreamReady: (ready: boolean) => ({
    type: STREAMING_ACTIONS.SET_STREAM_READY,
    payload: ready,
  }),

  setConnecting: (connecting: boolean) => ({
    type: STREAMING_ACTIONS.SET_CONNECTING,
    payload: connecting,
  }),

  setConnected: (connected: boolean) => ({
    type: STREAMING_ACTIONS.SET_CONNECTED,
    payload: connected,
  }),

  setStreamConfig: (config: StreamConnectionConfig) => ({
    type: STREAMING_ACTIONS.SET_STREAM_CONFIG,
    payload: config,
  }),

  updateStreamSettings: (
    settings: Partial<{
      width: number;
      height: number;
      fps: number;
      nativeTouchEvents: boolean;
    }>
  ) => ({
    type: STREAMING_ACTIONS.UPDATE_STREAM_SETTINGS,
    payload: settings,
  }),

  setAudioMuted: (muted: boolean) => ({
    type: STREAMING_ACTIONS.SET_AUDIO_MUTED,
    payload: muted,
  }),

  setVideoMuted: (muted: boolean) => ({
    type: STREAMING_ACTIONS.SET_VIDEO_MUTED,
    payload: muted,
  }),

  setMicrophoneEnabled: (enabled: boolean) => ({
    type: STREAMING_ACTIONS.SET_MICROPHONE_ENABLED,
    payload: enabled,
  }),

  updateConnectionQuality: (quality: StreamingState['connectionQuality']) => ({
    type: STREAMING_ACTIONS.UPDATE_CONNECTION_QUALITY,
    payload: quality,
  }),

  updateStreamMetrics: (metrics: {
    latency?: number;
    bitrate?: number;
    frameRate?: number;
  }) => ({
    type: STREAMING_ACTIONS.UPDATE_STREAM_METRICS,
    payload: metrics,
  }),

  setConnectionError: (error: string) => ({
    type: STREAMING_ACTIONS.SET_CONNECTION_ERROR,
    payload: error,
  }),

  clearConnectionError: () => ({
    type: STREAMING_ACTIONS.CLEAR_CONNECTION_ERROR,
  }),

  addStreamEvent: (event: Omit<StreamEvent, 'timestamp'>) => ({
    type: STREAMING_ACTIONS.ADD_STREAM_EVENT,
    payload: {
      ...event,
      timestamp: Date.now(),
    },
  }),

  resetStreamingState: () => ({
    type: STREAMING_ACTIONS.RESET_STREAMING_STATE,
  }),
};

// Reducer function (simplified version without Redux Toolkit)
// Define a union type for all possible action payloads
type StreamingAction =
  | { type: typeof STREAMING_ACTIONS.SET_STREAM_READY; payload: boolean }
  | { type: typeof STREAMING_ACTIONS.SET_CONNECTING; payload: boolean }
  | { type: typeof STREAMING_ACTIONS.SET_CONNECTED; payload: boolean }
  | {
      type: typeof STREAMING_ACTIONS.SET_STREAM_CONFIG;
      payload: StreamConnectionConfig;
    }
  | {
      type: typeof STREAMING_ACTIONS.UPDATE_STREAM_SETTINGS;
      payload: Partial<{
        width: number;
        height: number;
        fps: number;
        nativeTouchEvents: boolean;
      }>;
    }
  | { type: typeof STREAMING_ACTIONS.SET_AUDIO_MUTED; payload: boolean }
  | { type: typeof STREAMING_ACTIONS.SET_VIDEO_MUTED; payload: boolean }
  | { type: typeof STREAMING_ACTIONS.SET_MICROPHONE_ENABLED; payload: boolean }
  | {
      type: typeof STREAMING_ACTIONS.UPDATE_CONNECTION_QUALITY;
      payload: StreamingState['connectionQuality'];
    }
  | {
      type: typeof STREAMING_ACTIONS.UPDATE_STREAM_METRICS;
      payload: { latency?: number; bitrate?: number; frameRate?: number };
    }
  | { type: typeof STREAMING_ACTIONS.SET_CONNECTION_ERROR; payload: string }
  | { type: typeof STREAMING_ACTIONS.CLEAR_CONNECTION_ERROR }
  | { type: typeof STREAMING_ACTIONS.INCREMENT_RECONNECT_ATTEMPTS }
  | { type: typeof STREAMING_ACTIONS.RESET_RECONNECT_ATTEMPTS }
  | { type: typeof STREAMING_ACTIONS.ADD_STREAM_EVENT; payload: StreamEvent }
  | { type: typeof STREAMING_ACTIONS.CLEAR_STREAM_EVENTS }
  | { type: typeof STREAMING_ACTIONS.RESET_STREAMING_STATE };

// Type guard to check if action is StreamingAction
function isStreamingAction(action: unknown): action is StreamingAction {
  if (action === null || typeof action !== 'object' || !('type' in action)) {
    return false;
  }
  const actionType = (action as { type: unknown }).type;
  return typeof actionType === 'string' &&
         (Object.values(STREAMING_ACTIONS) as string[]).includes(actionType);
}

export const streamingReducer = (
  state: StreamingState = initialState,
  action: unknown
): StreamingState => {
  // Only process known streaming actions
  if (!isStreamingAction(action)) {
    return state;
  }

  switch (action.type) {
    case STREAMING_ACTIONS.SET_STREAM_READY:
      return {
        ...state,
        streamReady: action.payload,
      };

    case STREAMING_ACTIONS.SET_CONNECTING:
      return {
        ...state,
        isConnecting: action.payload,
        lastConnectionAttempt: action.payload
          ? Date.now()
          : state.lastConnectionAttempt,
      };

    case STREAMING_ACTIONS.SET_CONNECTED:
      return {
        ...state,
        isConnected: action.payload,
        isConnecting: false,
        connectionError: action.payload ? null : state.connectionError,
        reconnectAttempts: action.payload ? 0 : state.reconnectAttempts,
      };

    case STREAMING_ACTIONS.SET_STREAM_CONFIG:
      return {
        ...state,
        ...action.payload,
      };

    case STREAMING_ACTIONS.UPDATE_STREAM_SETTINGS:
      return {
        ...state,
        ...action.payload,
      };

    case STREAMING_ACTIONS.SET_AUDIO_MUTED:
      return {
        ...state,
        audioMuted: action.payload,
      };

    case STREAMING_ACTIONS.SET_VIDEO_MUTED:
      return {
        ...state,
        videoMuted: action.payload,
      };

    case STREAMING_ACTIONS.SET_MICROPHONE_ENABLED:
      return {
        ...state,
        microphoneEnabled: action.payload,
      };

    case STREAMING_ACTIONS.UPDATE_CONNECTION_QUALITY:
      return {
        ...state,
        connectionQuality: action.payload,
      };

    case STREAMING_ACTIONS.UPDATE_STREAM_METRICS:
      return {
        ...state,
        ...action.payload,
      };

    case STREAMING_ACTIONS.SET_CONNECTION_ERROR:
      return {
        ...state,
        connectionError: action.payload,
        isConnecting: false,
      };

    case STREAMING_ACTIONS.CLEAR_CONNECTION_ERROR:
      return {
        ...state,
        connectionError: null,
      };

    case STREAMING_ACTIONS.INCREMENT_RECONNECT_ATTEMPTS:
      return {
        ...state,
        reconnectAttempts: state.reconnectAttempts + 1,
      };

    case STREAMING_ACTIONS.RESET_RECONNECT_ATTEMPTS:
      return {
        ...state,
        reconnectAttempts: 0,
      };

    case STREAMING_ACTIONS.ADD_STREAM_EVENT:
      return {
        ...state,
        streamEvents: [
          ...state.streamEvents.slice(-49), // Keep last 50 events
          action.payload,
        ],
      };

    case STREAMING_ACTIONS.CLEAR_STREAM_EVENTS:
      return {
        ...state,
        streamEvents: [],
      };

    case STREAMING_ACTIONS.RESET_STREAMING_STATE:
      return initialState;

    default:
      return state;
  }
};

// Selectors
export const selectStreamReady = (state: { streaming: StreamingState }) =>
  state.streaming.streamReady;
export const selectIsConnected = (state: { streaming: StreamingState }) =>
  state.streaming.isConnected;
export const selectIsConnecting = (state: { streaming: StreamingState }) =>
  state.streaming.isConnecting;
export const selectConnectionQuality = (state: { streaming: StreamingState }) =>
  state.streaming.connectionQuality;
export const selectStreamMetrics = (state: { streaming: StreamingState }) => ({
  latency: state.streaming.latency,
  bitrate: state.streaming.bitrate,
  frameRate: state.streaming.frameRate,
});
export const selectStreamEvents = (state: { streaming: StreamingState }) =>
  state.streaming.streamEvents;
export const selectConnectionError = (state: { streaming: StreamingState }) =>
  state.streaming.connectionError;

export default streamingReducer;
