{{- if .Values.envoy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bottle-filling-twin.envoyConfigMapName" . }}
  namespace: {{ include "bottle-filling-twin.namespace" . }}
  labels:
    # Mandatory labels: ensure `app` and `sessionId` are always present.
    app: {{ include "bottle-filling-twin.name" . }}-{{ .Values.streamingKit.sessionId }}
    sessionId: {{ .Values.streamingKit.sessionId }}
    {{- include "bottle-filling-twin.labels" . | nindent 4 }}
    app.kubernetes.io/component: envoy
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: webrtc_signaling_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.envoy.proxyPort }}
        filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp
              cluster: kit_app_cluster
              access_log:
                - name: envoy.access_loggers.stream
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                    log_format:
                      text_format: "[%START_TIME%] \"%PROTOCOL%\" connection from %DOWNSTREAM_REMOTE_ADDRESS% to %UPSTREAM_HOST%\n"
      - name: health_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.envoy.healthPort }}
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: health_check
              codec_type: AUTO
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/health"
                    direct_response:
                      status: 200
                      body:
                        inline_string: "OK"
              http_filters:
              - name: envoy.filters.http.router
      clusters:
      - name: kit_app_cluster
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: kit_app_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: {{ .Values.kitApp.ports.signaling }}
{{- end }}
